name: Merge Bot

on:
  pull_request:
    types: [labeled, unlabeled, review_request_removed]
    
jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.2.0
      with:
        GITHUB_TOKEN: ${{ secrets.GH_TOK }}
        test: false
        reviewers: false
        labels: automerge
        method: merge
