name: Automerge
on: 
  pull_request:
    types: [labeled]
    branches:
      - l10n_master      # The branch you want to automatically merge pull request
jobs:
  Run Actions:
    runs-on: [ubuntu-latest]
    steps:
    - name: Automatically Merge PR
      uses: plm9606/automerge_actions@1.0.0
      with:
        github-token: ${{ secrets.GH_TOK }}
