name: Copy integration.home-assistant translated files
on:
  pull_request:
    types:
      - closed
jobs:
  copycat:
    name: Copycat
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v1.1.0
      env:
        DST_BRANCH: dev
        DST_OWNER: YIO-Remote
        DST_REPO_NAME: integration.home-assistant
        DST_PATH: /translations/
        GH_PAT: ${{ secrets.GH_TOK }}
        SRC_BRANCH: master
        SRC_PATH: /remote-software/translated/*.ts
        USERNAME: Workflow
        EMAIL: hello@yio-remote.com
