name: Copy remote-software translated files
on:
  pull_request:
    types:
      - closed
jobs:
  copycat:
    name: Copycat
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        dst_branch: master
        dst_owner: YIO-Remote
        dst_repo_name: remote-software
        dst_path: /translations/
        personal_token: ${{ secrets.GH_TOKEN }}
        src_branch: master
        src_path: /remote-software/translated/*.ts
        username: Workflow
        email: hello@yio-remote.com
        commit_message: 'ci: New translations'
