name: Copy tranlsation files back to remote-software repo
on: push
jobs:
  copycat:
    name: Copycat
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copycat
      uses: andstor/copycat-action@v1.1.0
      env:
        DST_BRANCH: dev
        DST_OWNER: YIO-Remote
        DST_REPO_NAME: remote-software
        DST_PATH: /translations/
        GH_PAT: ${{ secrets.GH_PAT }}
        SRC_BRANCH: master
        SRC_PATH: /remote-software/translated/
        USERNAME: Workflow
        EMAIL: hello@yio-remote.com
