name: Copy integration.homey translated files
on:
  schedule:
    - cron: "0 23 * * *"
jobs:
  copycat:
    name: Copycat
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        dst_branch: master
        dst_owner: YIO-Remote
        dst_repo_name: integration.homey
        dst_path: /translations/
        personal_token: ${{ secrets.GH_TOKEN }}
        src_branch: master
        src_path: /integration.homey/translated/.
        file_filter: '*.ts'
        username: Workflow
        email: hello@yio-remote.com
        commit_message: 'ci: New translations'
