name: Auto merge

on:
  pull_request:
    types: [labeled, unlabeled, review_request_removed]
  pull_request_review:

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GH_TOK }}
        number: 1
        method: merge
